INSERT INTO `staffs_items` (`id`, `name`, `type_name`, `status`) VALUES
(1,	'HN',	'Location',	1),
(2,	'HCM',	'Location',	1),
(3,	'HD Thử việc',	'Contract',	1),
(4,	'HĐLĐ xác định thời hạn 12 tháng',	'Contract',	1),
(5,	'HĐLĐ XĐTH trên 12T đến 36T',	'Contract',	1),
(6,	'HĐLĐ XĐTH trên 12T-36T',	'Contract',	1),
(7,	'HĐLĐ Không xác định thời hạn',	'Contract',	1),
(8,	'HĐ Thực tập',	'Contract',	1),
(9,	'Đang làm việc',	'Work',	1),
(10,	'Nghỉ tạm - thai sản',	'Work',	1),
(11,	'Nghỉ tạm - không lương',	'Work',	1),
(12,	'Nghỉ việc - gia đình',	'Work',	1),
(13,	'Nghỉ việc - vì học tiếp',	'Work',	1),
(14,	'Nghỉ việc - định hướng mới',	'Work',	1),
(15,	'Nghỉ việc - do thanh lý',	'Work',	1),
(16,	'SU01',	'Department',	1),
(17,	'SU02',	'Department',	1),
(18,	'SU03',	'Department',	1),
(19,	'SU04',	'Department',	1),
(20,	'SU06',	'Department',	1),
(21,	'SU08',	'Department',	1),
(22,	'SU10',	'Department',	1),
(23,	'SU12',	'Department',	1),
(24,	'OSU02',	'Department',	1),
(25,	'OSU04',	'Department',	1),
(26,	'OSU06',	'Department',	1),
(27,	'SQMU',	'Department',	1),
(28,	'SYS',	'Department',	1),
(29,	'FOXPAY',	'Department',	1),
(30,	'FTQ',	'Department',	1),
(31,	'INF',	'Department',	1),
(32,	'NOC',	'Department',	1),
(33,	'PAYTV',	'Department',	1),
(34,	'SCC',	'Department',	1),
(35,	'Khối R&D',	'Department',	1),
(36,	'Khối Dịch vụ',	'Department',	1),
(37,	'Khối Hệ thống',	'Department',	1),
(38,	'Khối Vận hành',	'Department',	1),
(39,	'ISC',	'Center',	1),
(40,	'FOXPAY',	'Center',	1),
(41,	'FTQ',	'Center',	1),
(42,	'INF',	'Center',	1),
(43,	'NOC',	'Center',	1),
(44,	'PAYTV',	'Center',	1),
(45,	'SCC',	'Center',	1);